GRANT ALL ON *.* TO kleinp@'127.0.0.1' IDENTIFIED BY 'abc123' WITH GRANT OPTION;
GRANT ALL ON *.* TO kleinp@'localhost' IDENTIFIED BY 'abc123' WITH GRANT OPTION;
GRANT ALL ON *.* TO kleinp@'::1' IDENTIFIED BY 'abc123' WITH GRANT OPTION;
DELETE FROM mysql.user WHERE User='';
DROP DATABASE test;
FLUSH PRIVILEGES;
